name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Update wrangler.toml
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_WORKER_NAME: ${{ secrets.CF_WORKER_NAME }}
        run: |
          sed -i 's/CF_ACCOUNT_ID/'"$CF_ACCOUNT_ID"'/' wrangler.toml
          sed -i 's/CF_WORKER_NAME/'"$CF_WORKER_NAME"'/' wrangler.toml
      
      - name: Build
        run: |
          npm install && npm run build

      - name: Publish Worker
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.7.0'
